{
  "sksl": {
    "entrypoint": "flash_transition_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float iTime;\nuniform float iFlashIntensity;\nuniform float uPixelRatio;\nuniform shader iChannel0;\nuniform half2 iChannel0_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 c = FLT_flutter_local_FlutterFragCoord();\n    vec2 pos = c / vec2(uPixelRatio);\n    vec2 uv = vec2(pos.x, iResolution.y - pos.y) / iResolution;\n    vec2 center = vec2(0.5);\n    float dist = distance(uv, center);\n    float aberration = (iFlashIntensity * dist) * 0.014999999664723873138427734375;\n    vec2 uvR = uv + (((uv - center) * aberration) * 1.0);\n    vec2 uvG = uv + (((uv - center) * aberration) * 0.5);\n    vec2 uvB = uv + (((uv - center) * aberration) * 0.0);\n    float r = iChannel0.eval(iChannel0_size * ( vec2(uvR.x, 1.0 - uvR.y))).x;\n    float g = iChannel0.eval(iChannel0_size * ( vec2(uvG.x, 1.0 - uvG.y))).y;\n    float b = iChannel0.eval(iChannel0_size * ( vec2(uvB.x, 1.0 - uvB.y))).z;\n    vec3 sceneColor = vec3(r, g, b);\n    vec3 flashColor = vec3(1.0);\n    float mixFactor = pow(iFlashIntensity, 3.0);\n    vec3 finalColor = mix(sceneColor, flashColor, vec3(pow(iFlashIntensity, 3.0)));\n    float vignette = 1.0 - ((dist * iFlashIntensity) * 0.300000011920928955078125);\n    finalColor *= vignette;\n    fragColor = vec4(finalColor, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "iTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "iFlashIntensity",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uPixelRatio",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 4,
        "name": "iChannel0",
        "rows": 1,
        "type": 12
      }
    ]
  }
}