{
  "sksl": {
    "entrypoint": "logo_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform shader uLogoTexture;\nuniform half2 uLogoTexture_size;\n\nvec4 fragColor;\n\nfloat FLT_flutter_local_getAlphaSDF(vec2 uv)\n{\n    bool _21 = uv.x < 0.0;\n    bool _29;\n    if (!_21)\n    {\n        _29 = uv.x > 1.0;\n    }\n    else\n    {\n        _29 = _21;\n    }\n    bool _37;\n    if (!_29)\n    {\n        _37 = uv.y < 0.0;\n    }\n    else\n    {\n        _37 = _29;\n    }\n    bool _44;\n    if (!_37)\n    {\n        _44 = uv.y > 1.0;\n    }\n    else\n    {\n        _44 = _37;\n    }\n    if (_44)\n    {\n        return 0.0;\n    }\n    float distance = uLogoTexture.eval(uLogoTexture_size * ( uv)).w;\n    float edgeWidth = 0.5;\n    float alpha = smoothstep(0.5 - edgeWidth, 0.5 + edgeWidth, distance);\n    return alpha;\n}\n\nvoid FLT_main()\n{\n    vec2 uv_1 = flutter_FragCoord.xy / uSize;\n    vec2 param = uv_1;\n    float alpha_1 = FLT_flutter_local_getAlphaSDF(param);\n    fragColor = vec4(1.0) * alpha_1;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 1,
        "name": "uLogoTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}