{
  "sksl": {
    "entrypoint": "metallic_text_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform vec2 uOffset;\nuniform float uTime;\nuniform vec3 uBaseColor;\nuniform float uOpacity;\nuniform vec2 uLightPos;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec4 FLT_flutter_local_tanh_polyline(vec4 x)\n{\n    vec4 val = clamp(x, vec4(-20.0), vec4(20.0));\n    vec4 ex = exp(val);\n    vec4 emx = exp(-val);\n    return (ex - emx) / (ex + emx);\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 localCoord = fragCoord - uOffset;\n    vec2 uv = localCoord / uSize;\n    float edgeShadow = max(0.4000000059604644775390625, 1.0 - pow(abs(uv.y - 0.5) * 2.0, 3.0));\n    vec3 color = uBaseColor * edgeShadow;\n    float dx = abs(fragCoord.x - uLightPos.x);\n    float dy = abs(fragCoord.y - uLightPos.y);\n    float dist = sqrt((dx * dx) + ((dy * dy) * 0.300000011920928955078125));\n    float lightRadius = 800.0;\n    float glow = smoothstep(lightRadius, 0.0, dist);\n    float glint = pow(glow, 60.0) * 25.0;\n    float ambientGlow = 1.0 - glow;\n    vec3 lightColor = vec3(1.0);\n    color += (lightColor * (ambientGlow + glint));\n    vec4 param = vec4(color, 1.0);\n    vec4 finalResult = FLT_flutter_local_tanh_polyline(param);\n    fragColor = vec4(finalResult.xyz * uOpacity, uOpacity);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uOffset",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uBaseColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uOpacity",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uLightPos",
        "rows": 2,
        "type": 10
      }
    ]
  }
}