{
  "sksl": {
    "entrypoint": "shine_text_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform vec2 uOffset;\nuniform float uTime;\nuniform vec3 uBaseColor;\nuniform float uOpacity;\nuniform vec2 uLightPos;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec4 FLT_flutter_local_tanh_polyline(vec4 x)\n{\n    vec4 val = clamp(x, vec4(-20.0), vec4(20.0));\n    vec4 ex = exp(val);\n    vec4 emx = exp(-val);\n    return (ex - emx) / (ex + emx);\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 localCoord = fragCoord - uOffset;\n    vec2 uv = localCoord / uSize;\n    uv = clamp(uv, vec2(0.0), vec2(1.0));\n    float horizon = 0.0;\n    float y = uv.y;\n    if (y < 0.5)\n    {\n        horizon = mix(0.800000011920928955078125, 0.20000000298023223876953125, smoothstep(0.0, 0.5, y));\n    }\n    else\n    {\n        horizon = mix(0.0, 0.5, smoothstep(0.5, 1.0, y));\n    }\n    vec3 baseColor = uBaseColor * horizon;\n    float dx = abs(localCoord.x - uLightPos.x);\n    float dy = abs(localCoord.y - uLightPos.y);\n    float dist = sqrt((dx * dx) + ((dy * dy) * 0.100000001490116119384765625));\n    float lightRadius = 1200.0;\n    float glow = smoothstep(lightRadius, 0.0, dist);\n    float glint = pow(glow, 6.0) * 12.0;\n    float ambientGlow = 0.100000001490116119384765625;\n    vec3 lightColor = vec3(1.0);\n    vec3 color = baseColor + (lightColor * (ambientGlow + glint));\n    vec4 param = vec4(color, 1.0);\n    vec4 finalResult = FLT_flutter_local_tanh_polyline(param);\n    fragColor = vec4(finalResult.xyz * uOpacity, uOpacity);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uOffset",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uBaseColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uOpacity",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uLightPos",
        "rows": 2,
        "type": 10
      }
    ]
  }
}